### PR TITLE
fix issue #35

### PR DESCRIPTION
**Pull request by ilyarolf**

### CODE REVIEW

**Comment by turazashvili** [comment]
Seems like fixed! thanks

**Comment by hoianstyle** [comment]
Hi @ilyarolf , Can you give me a demo of AIOshopbot? Could u please help me install it (for a fee), is that possible?

**Comment by ilyarolf** [comment]
@hoianstyle Yes, it's possible. Send your telegram username to me at ilyarolf@mail.ru. I will message you in telegram.

**Comment by hoianstyle** [comment]
@ilyarolf Check your email plz

**Comment by ilyarolf** [comment]
@hoianstyle Texted you a telegram message at 7:48 UTC

**Pull request merged**
